# Generated by Django 2.0.3 on 2020-06-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regularpizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64)),
                ('smallcost', models.FloatField()),
                ('largecost', models.FloatField()),
                ('ntoppings', models.IntegerField()),
            ],
        ),
    ]
