# Generated by Django 3.0.6 on 2020-06-06 14:03

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_regularpizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinnerplatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64, unique=True)),
                ('smallcost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
                ('largecost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('smallcost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
                ('largecost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingname', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='largecost',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='ntoppings',
            field=models.IntegerField(default=0, validators=[orders.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='smallcost',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive]),
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
                ('extras', models.ManyToManyField(blank=True, to='orders.Extra')),
            ],
        ),
        migrations.CreateModel(
            name='Sicilianpizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64, unique=True)),
                ('smallcost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
                ('largecost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
                ('ntoppings', models.IntegerField(default=0, validators=[orders.models.is_positive])),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
