# Generated by Django 3.0.6 on 2020-06-06 23:06

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200606_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs',
            old_name='cost',
            new_name='smallcost',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='subs',
            name='extras',
        ),
        migrations.AddField(
            model_name='subs',
            name='largecost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[orders.models.is_positive]),
            preserve_default=False,
        ),
    ]
