# Generated by Django 3.0.6 on 2020-06-06 23:31

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200607_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='smallcost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[orders.models.is_positive]),
        ),
    ]
