# Generated by Django 3.0.6 on 2020-06-10 00:39

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200607_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatter',
            name='ntoppings',
            field=models.IntegerField(default=0, validators=[orders.models.is_positive]),
        ),
        migrations.AddField(
            model_name='extra',
            name='ntoppings',
            field=models.IntegerField(default=0, validators=[orders.models.is_positive]),
        ),
        migrations.AddField(
            model_name='pasta',
            name='ntoppings',
            field=models.IntegerField(default=0, validators=[orders.models.is_positive]),
        ),
        migrations.AddField(
            model_name='salad',
            name='ntoppings',
            field=models.IntegerField(default=0, validators=[orders.models.is_positive]),
        ),
        migrations.AddField(
            model_name='subs',
            name='ntoppings',
            field=models.IntegerField(default=0, validators=[orders.models.is_positive]),
        ),
    ]
