# Generated by Django 3.0.6 on 2020-06-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200610_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatter',
            name='extrasEnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pasta',
            name='extrasEnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='extrasEnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salad',
            name='extrasEnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='extrasEnable',
            field=models.BooleanField(default=False),
        ),
    ]
