# Generated by Django 3.0.6 on 2020-06-24 16:39

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200610_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='ntoppings',
            field=models.IntegerField(default=0, validators=[orders.models.is_positive]),
        ),
    ]
