# Generated by Django 3.0.6 on 2020-06-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_pasta_ntoppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='ntoppings',
        ),
    ]
