# Generated by Django 3.0.6 on 2020-06-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_extra_ntoppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='name',
            new_name='itemname',
        ),
    ]
