# Generated by Django 3.0.6 on 2020-06-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200625_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta',
            old_name='cost',
            new_name='smallcost',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='cost',
            new_name='smallcost',
        ),
    ]
