# Generated by Django 3.0.6 on 2020-06-25 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0018_auto_20200625_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64)),
                ('cat', models.CharField(max_length=64)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
                ('extras', models.ManyToManyField(blank=True, to='orders.Extra')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, validators=[orders.models.is_positive])),
                ('status', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
                ('items', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
